#ifndef CONSTANTS_H
#define CONSTANTS_H

#define COLS 10  
#define ROWS 14  

#define HOLD_PIECE_WIDTH 80 
#define NEXT_PIECE_WIDTH 80  
#define SCORE_UI_HEIGHT 100  

#define SCREEN_WIDTH (COLS * BLOCK_SIZE + HOLD_PIECE_WIDTH + NEXT_PIECE_WIDTH)
#define SCREEN_HEIGHT (ROWS * BLOCK_SIZE + SCORE_UI_HEIGHT)

#define BLOCK_SIZE 30

#endif
